### ISSUE TITLE
ChEMBL in OXO?

### ISSUE THREAD

**Issue by janelomax** [EBISPOT/OLS-mapping-service#10]
Hi - is there any possibility of including ChEMBL in OXO?

cheers

Jane

**Comment by simonjupp** [comment]
What mappings to chembl are you thinking, chebi? I'd just need a source to get these from then we could have a custom loader into OxO. 

I want to restrict OxO to just ontology 2 ontology or ontology 2 database mappings. There are other services doing database 2 database mappings.

**Comment by janelomax** [comment]
Yeah, I was just thinking Chembl to ChEBI.

Looks like both ChEBI and ChEMBL get their xrefs here:

https://www.ebi.ac.uk/unichem/

There's an API or you can just download the full mappings here:

ftp://ftp.ebi.ac.uk/pub/databases/chembl/UniChem/data/wholeSourceMapping/

ChEMBL is src_id1 and ChEBI is src_id7

So in fact I hadn't realised it was this easy, I can get everything I need from unichem no need to add to OXO (unless you think it's useful for other users) so you can close this ticket!

**Comment by simonjupp** [comment]
that's good to know actually. We might still add the chebi chembl xrefs. thanks
