### ISSUE TITLE
no label displayed for SNOMED CT terms

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS-mapping-service#15]
See attached, using the HP term example from the website.

<img width="1225" alt="screen shot 2018-01-09 at 13 59 46" src="https://user-images.githubusercontent.com/2214135/34724383-89ef88de-f545-11e7-8238-9f85c9887fe1.png">

I would expect the label from https://snomedbrowser.com/Codes/Details/44054006 to be displayed.

**Comment by mcourtot** [comment]
Maybe related to #2?

**Comment by LLTommy** [comment]
Yes, once we do the new data release - which hopefully happens soon (around end of January) - this problem should go away.
