### ISSUE TITLE
OxO stats?

### ISSUE THREAD

**Issue by mcourtot** [EBISPOT/OLS-mapping-service#16]
Hi - as I'm trying to tell people to use OxO for their mapping needs, it would be useful to have some sort of stats in support of this. For example, how much of HPO has been mapped to SNOMED? I'm not sure this is the right stat either, as they may have branches that are non-relevant to each other. I'm wondering if you thought about how to quantitatively assess OxO and if you could share some of those numbers? If not done yet I'm happy to try and contribute to discussion of these.

**Comment by simonjupp** [comment]
Have you seen this page? https://www.ebi.ac.uk/spot/oxo/datasources/HP you can get stats for mappings between individual ontologies. Distance 1 are direct mappings, distance 2 are indirect mappings.

**Comment by mcourtot** [comment]
No I hadn't! To be honest I couldn't find HPO easily on the circular diagram on the front page so it was hard as well to tell people which resources it was mapped to, which is why I used the sample query instead.
I see I can get a list of all the mappings by clicking on the chart bars, this is great!

**Comment by LLTommy** [comment]
There is a 'Jump to a datasource' box above the diagram, if you enter e.g. "human phenotype ontology" it helps you to jump to a datasource (instead of looking for an ontology in the diagram).

**Comment by simonjupp** [comment]
there is also a datasource search/dropdown to find an ontology above the diagram. We'll look into making that more obvious.

**Comment by mcourtot** [comment]
I'm probably the painful nagging user atm, but it didn't find 'HPO' in that box, then I had to use the full name  which was meh. Maybe we should consider a joint UX session - we have many issues on the biosd side and would really benefit from this.
Anyway, thanks for the feedback!
