### ISSUE TITLE
Ontology labels missing

### ISSUE THREAD

**Issue by janelomax** [EBISPOT/OLS-mapping-service#2]
Hi - some of the NCIt names aren't showing up in OXO (see attached screenshot). If you follow the link to the source, the nameless terms do seem to be current and have names e.g.:

https://ncit.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI%20Thesaurus&code=C100436

cheers

Jane
![screen shot 2017-04-27 at 14 26 50](https://cloud.githubusercontent.com/assets/6639811/25485542/3574b9f0-2b56-11e7-9341-3599a95ef7e2.png)

**Comment by janelomax** [comment]
Changed the title of this as it seems that the missing labels aren't limited to NCIt, for example most of the ICD9 and ICD10 labels are missing.

It this something that's likely to be quick/easy to fix? I'm trying to decide whether to build a work around or wait!

**Comment by simonjupp** [comment]
We need to reload all the datasources, we're still a couple of weeks away from being ready to do that. I expect this to happen in early October now, I'll keep you posted.

**Comment by janelomax** [comment]
Awesome, keep me posted.
